inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
