language: ruby
rvm:
  - 2.2.3

# Если Travis пишет вам слишком часто, то отключаем email уведомления
notifications:
  email: false

# Указываем базу данных
addons:
  postgresql: "9.4"

# Аргументы для bundler
bundler_args: --without development --deployment --jobs=3 --retry=3

# Кэшируем гемы, чтобы не устанавливать каждый раз все заново
cache: bundler

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  # Создаем базу
  - psql -c 'create database qna_test;' -U postgres
  # Копируем конфиги
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - cp config/private_pub.yml.sample config/private_pub.yml
  - cp config/thinking_sphinx.yml.sample config/thinking_sphinx.yml
  # Формируем структуру базы
  - bundle exec rake db:setup
  # Запускаем PrivatePub
  - 'bundle exec rackup private_pub.ru -s thin -E production &'
  # Ждем, пока PrivatePub проинициализируется
  - sleep 3

gemfile:
  - Gemfile
