version: '3.9'

x-app: &app
  platform: linux/amd64
  build:
    context: .
    args:
      RUBY_VERSION: 3.2.0
      NODE_VERSION: 18.12.1
      BUNDLER_VERSION: 2.3.26
  image: heapoverflow:2.0.6
  stdin_open: true
  tty: true
  restart: unless-stopped
  environment:
    DATABASE_URL: postgres://postgres:some-long-secure-password@postgres:5432
    REDIS_URL: redis://redis:6379
    ELASTICSEARCH_URL: http://elasticsearch:9200
  volumes:
    - .:/usr/src/app
    - bundle:/usr/local/bundle
  tmpfs:
    - /usr/src/app/tmp/pids
  depends_on:
    - postgres
    - redis
    - elasticsearch

services:
  web:
    <<: *app
    ports:
      - 3000:3000
    command: bin/dev

  sidekiq:
    <<: *app
    command: bundle exec sidekiq

  mailcatcher:
    image: sj26/mailcatcher:v0.8.2
    ports:
      - 1080:1080

  postgres:
    image: postgres:15.1
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: some-long-secure-password
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis:/data

  elasticsearch:
    image: elasticsearch:8.5.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 500M

  chrome:
    image: browserless/chrome:latest
    restart: unless-stopped
    ports:
      - 4444:4444
    volumes:
      - .:/app:cached
    environment:
      PORT: 4444

volumes:
  bundle:
  postgres:
  redis:
