version: '3.9'

services:
  web:
    build: .
    image: heapoverflow:2.0.4
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:some-long-secure-password@postgres:5432
      REDIS_URL: redis://redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    tmpfs:
      - /usr/src/app/tmp/pids
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: bin/dev

  sidekiq:
    build: .
    image: heapoverflow:2.0.4
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:some-long-secure-password@postgres:5432
      REDIS_URL: redis://redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: bundle exec sidekiq

  postgres:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: some-long-secure-password
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis:/data

  elasticsearch:
    image: elasticsearch:8.5.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 500M

  chrome:
    image: seleniarm/standalone-chromium:107.0
    restart: unless-stopped
    environment:
      SE_VNC_NO_PASSWORD: 1
    volumes:
      - .:/usr/src/app
    ports:
      - '7900:7900'

volumes:
  bundle:
  postgres:
  redis:
