version: '3.9'

services:
  web:
    build: .
    image: heapoverflow:2.0.1
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:some-long-secure-password@postgres:5432
      REDIS_URL: redis://redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    tmpfs:
      - /usr/src/app/tmp/pids
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: bundle exec rails server -b 0.0.0.0

  sidekiq:
    build: .
    image: heapoverflow:2.0.1
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://postgres:some-long-secure-password@postgres:5432
      REDIS_URL: redis://redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: bundle exec sidekiq

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: some-long-secure-password
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis:/data

  elasticsearch:
    image: elasticsearch:8.5.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200

  chrome:
    image: seleniarm/standalone-chromium:107.0
    environment:
      SE_VNC_NO_PASSWORD: 1
    volumes:
      - .:/usr/src/app
    ports:
      - '7900:7900'

volumes:
  bundle:
  postgres:
  redis:
