version: '3.9'

services:
  web:
    build: .
    image: heapoverflow:2.0.0
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:some-long-secure-password@postgres:5432
      FAYE_PUBLIC_URL: http://localhost:9292/faye
      REDIS_URL: redis://redis:6379
      SPHINX_HOST: '0.0.0.0'
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    tmpfs:
      - /usr/src/app/tmp/pids
    depends_on:
      - postgres
      - redis
    command: /bin/bash -c "bundle exec rails ts:start; bundle exec rails server -b 0.0.0.0"

  sidekiq:
    build: .
    image: heapoverflow:2.0.0
    environment:
      DATABASE_URL: postgres://postgres:some-long-secure-password@postgres:5432
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    depends_on:
      - postgres
      - redis
    command: bundle exec sidekiq

  private_pub:
    build: .
    image: heapoverflow:2.0.0
    ports:
      - '9292:9292'
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    command: rackup private_pub.ru -s thin -E production -o 0.0.0.0

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: some-long-secure-password
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis:/data

  chrome:
    image: seleniarm/standalone-chromium:107.0
    environment:
      SE_VNC_NO_PASSWORD: 1
    volumes:
      - .:/usr/src/app
    ports:
      - '7900:7900'

volumes:
  bundle:
  postgres:
  redis:
