x-app: &app
  platform: linux/amd64
  build:
    context: .
    args:
      RUBY_VERSION: 3.3.6
      NODE_VERSION: 22.11.0
      BUNDLER_VERSION: 2.5.23
  image: heapoverflow:2.2.0
  stdin_open: true
  tty: true
  restart: unless-stopped
  environment:
    DATABASE_URL: postgres://postgres:some-long-secure-password@postgres:5432
    REDIS_URL: redis://redis:6379
    ELASTICSEARCH_URL: http://elasticsearch:9200
  volumes:
    - .:/usr/src/app
    - bundle:/usr/local/bundle
  tmpfs:
    - /usr/src/app/tmp/pids
  depends_on:
    - postgres
    - elasticsearch

services:
  web:
    <<: *app
    ports:
      - 3000:3000
    command: bin/dev

  solid_queue:
    <<: *app
    command: bundle exec rake solid_queue:start

  mailcatcher:
    image: sj26/mailcatcher:v0.10.0
    ports:
      - 1080:1080

  postgres:
    image: postgres:17.1
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: some-long-secure-password
    volumes:
      - postgres:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:8.16.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 500M

  chrome:
    image: browserless/chrome:latest
    restart: unless-stopped
    ports:
      - 4444:4444
    volumes:
      - .:/app:cached
    environment:
      PORT: 4444

volumes:
  bundle:
  postgres:
